### PR TITLE
v2 velocity implementation

### PR DESCRIPTION
**Pull request by lefty71**
- [x] reassign program numbers
- [x] implement new min-max velocity mode
- [x] implement sysex serialization
- [x] implement cc message control
- [x] store midi channel with both midi learn modes
- [x] ensure midi learn mode works for i2cmidi
- [x] add support for automat mini
- [x] set default note configuration
- [x] add advanced capabilities sysex message
- [x] perform end to end testing

### CODE REVIEW

**Comment by jellea** [comment]
Yess! Very excited by this! @nevvkid shall we sit together and test this, some time this week?

**Comment by nevvkid** [comment]
I would love to get this out!
Still need someone to help with javascript to make the config tool look and behave like it should. The range is currently limited to 0 to 127. Because i could not implement the slider how it should look and behave. 
https://htmlpreview.github.io/?https://github.com/dadamachines/automat-configurator/blob/styling/index.html 
Which is apparently not like it should be. Best case the slider will be more like 0-100 (bigger steps) 200 / infinite. The infinite is very important here as that allows the behavior or 1.0.0 with the new firmware. So having noteOn/noteOff instead of a maximum gate length of 127. 
So this is actually the blocking issue. I just can't do it and have tooo much other things on my plate with composer.

**Comment by lefty71** [comment]
I could change the range from 0 to 127 to 0 to 100.   But I won't get to that until the second week of July.   Currently whenever someone sets the range to 0-0, I set the behavior to the infinite/1.0.0 behavior.

**Comment by nevvkid** [comment]
I was trying to test this today. But i can't get it working currently. I wrote a bit more in the forum. Maybe you can give me a hint how to test this? Thanks! J

**Review by sebs — COMMENTED** [review]
maybe generate a tag in the repo as well that reflects the 2.0.0 version

**Pull request merged**
